### ISSUE TITLE
Specify `sudo` as default for `docker compose up` (or Win equivalent)

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/mn-bootstrap#10]
**recreate**
(without sudo)
`docker-compose up`
```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**issue**
(Linux) Default docker installation requires `sudo`.
Resulting error message is unclear

**suggested fix**
Update readme.md to explain that `sudo` (or windows equivalent) may be required, or specify its use as relevant for each platform as default. i.e.:
On linux use  `sudo docker compose up`

**Comment by shumkov** [comment]
Yeah, we could mention it there https://docs.docker.com/install/linux/linux-postinstall/

**Comment by shumkov** [comment]
Fixed.
