### ISSUE TITLE
Sentinel image is broken

### ISSUE THREAD

**Issue by strophy** [dashevo/mn-bootstrap#14]
The current config uses the [`ablock/sentinel` image](https://hub.docker.com/r/ablock/sentinel), which I think is probably built from [here](https://github.com/codablock/docker-sentinel). I'm not sure what the specific problem is, but I'm getting the following sentinel error on both evonet and testnet:
```
Traceback (most recent call last):
  File "./bin/sentinel.py", line 227, in <module>
    main()
  File "./bin/sentinel.py", line 134, in main
    if not dashd.is_synced():
  File "lib/dashd.py", line 99, in is_synced
    mnsync_status['IsMasternodeListSynced'] and
KeyError: 'IsMasternodeListSynced'
```
I'm not sure what is causing this, it probably just hasn't been updated in 2 years. I have a working sentinel image at [`strophy/sentinel`](https://hub.docker.com/r/strophy/sentinel) ([source](https://github.com/strophy/docker-sentinel)), should we replace it with my image? Or should I work on updating the dashpay/sentinel image with PRs? Maybe we could take the chance to base it on the image as some of the platform stuff.

**Comment by shumkov** [comment]
Fixed https://github.com/dashevo/mn-bootstrap/pull/41
