### ISSUE TITLE
No Dash for the Evonet 

### ISSUE THREAD

**Issue by PanzerknackerR** [dashevo/mn-bootstrap#169]
With this function  " mn wallet:mint AMOUNT " you can only create Dash for LOCAL.

## Possible Solution

Change: 

    if (network !== NETWORKS.LOCAL) {
      throw new Error('Only local network supports generation of dash');
    }

to:

    if (network !== NETWORKS.LOCAL || network !== NETWORKS.EVONET) {
      throw new Error('Only local or evonet network supports generation of dash');
    }

## Steps to Reproduce (for bugs)

mn wallet:mint --config=evonet 1001

Results in: Error: Only local network supports generation of dash

## Context

To set up a master node you need 1000 dash.

**Comment by antouhou** [comment]
You can't do `generate` for evonet, as it's a real testnet network that uses real miner to mine coins. You can get evonet coins from a faucet: http://insight.evonet.networks.dash.org/

**Comment by RobinBuchta** [comment]
okey thanks for your answer. 

"If using a config specifying the local or evonet network, you can create and fund a new address using the wallet command as shown below."

Because of the sentence I assumed, the function would be wanted.
The documentation led me in the wrong direction.

**Comment by PanzerknackerR** [comment]
It seems that the code is fine, only the documentation was misleading.

**Comment by antouhou** [comment]
@PanzerknackerR Thank you for the suggestion! We'll update the docs
