### ISSUE TITLE
Enabling miner before running setup-for-local-development throws error

### ISSUE THREAD

**Issue by dashameter** [dashevo/mn-bootstrap#181]
Setting

```bash
node bin/mn config:set core.miner.address yfMr9oWYGLwAgdyuXUbTDE2bgXahCarMKG
node bin/mn config:set core.miner.enable true
```

before running `setup-for-local-development` throws:

```
  ✔ Wait 20 seconds to ensure all services are running
  ❯ Initialize Platform
    ✖ Failed to perform standard injections with reason: Worker IdentitySyncWorker failed onStart: Worker IdentitySyncWorker failed onExecute: No available addresses for retry: 13 INTERNAL: connect ECONNREFUSED…
    ◼ Register DPNS identity
    ◼ Register DPNS contract
    ◼ Obtain DPNS contract commit block height
    ◼ Register top level domain "dash"
    ◼ Disconnect SDK
  ◼ Stop node 
```

enabling the miner after first running `setup-for-local-development` works.

**Comment by strophy** [comment]
I cannot reproduce this from the current `master` branch. The miner starts fine and generates blocks at the specified interval and to the specified address, even if entered in the config before setting up for local development. @dashameter please ensure you have cleaned up any data and config left over from previous work, e.g. as follows:
```
mn config:default local
mn reset
mn config:reset
mn config:set core.miner.address yfMr9oWYGLwAgdyuXUbTDE2bgXahCarMKG
mn config:set core.miner.enable true
mn setup-for-local-development
mn start
```

Can you verify?

**Comment by dashameter** [comment]
I reset everything and tried it again and can confirm I now longer see this error thrown. I had reset and repeated this multiple times before when I saw this error, not sure if `master` updated in the meantime or if it was a bad config on my local machine that the reset didn't reset.. closing issue for now.
