### ISSUE TITLE
Reset command should remove tenderdash data files instead of `unsafe_reset_all`

### ISSUE THREAD

**Issue by shumkov** [dashevo/mn-bootstrap#271]
## Expected Behavior

`unsafe_reset_all` supposed to reset tenderdash state but it does it unsafely keeping something in the state which breaks further block production.

## Current Behavior

`unsafe_reset_all` is used in reset command

## Possible Solution

Delete all files from tenderdash `data` directory and generate new `priv_validator_state.json` with `tenderdash gen_validator` command.

## Your Environment

* Version used: v0.18
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.JS v12
* Operating System and version (desktop, server, or mobile): Mac OS

**Comment by strophy** [comment]
I don't think we currently use `unsafe_reset_all` in the reset command, where did you see this? We drop the volume and regenerate the validator state with `tenderdash init` instead.

**Comment by shumkov** [comment]
Oh... My bad.
