### ISSUE TITLE
Cannot reset --platform-only for single testnet node

### ISSUE THREAD

**Issue by strophy** [dashevo/mn-bootstrap#312]
It is not possible to `mn reset --platform-only` with a masternode single-node testnet config.

## Expected Behavior
Platform config is reset

## Current Behavior
Platform config is not reset, error thrown.

## Possible Solution
We probably need to enable platform services in config for non-group configs?

## Steps to Reproduce (for bugs)

1. Start a testnet node
2. Stop it
3. `mn reset --platform-only`
4. `Error: Cannot reset platform only if platform services are not enabled in config`.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by shumkov** [comment]
Which version/branch of mn-bootstrap do you use?

**Comment by strophy** [comment]
This is with `npm-cache` branch.

**Comment by shumkov** [comment]
Fixed in `npm-cache`
