### ISSUE TITLE
dashmate hangs during restart

### ISSUE THREAD

**Issue by dashameter** [dashevo/mn-bootstrap#430]
when running `dashmate group:stop` and later `dashmate group:start` dashmate hangs indefinitely at `forcing nodes to sync`

```
❯ Start local nodes
  ❯ Starting nodes
    ❯ Starting local_1 node
      ✔ Check node is not started
      ✔ Start services
      ✖ Force nodes to sync
    ❯ Starting local_2 node
      ✔ Check node is not started
      ✔ Start services
      ✖ Force nodes to sync
    ❯ Starting local_3 node
      ✔ Check node is not started
      ✔ Start services
      ✖ Force nodes to sync
    ❯ Starting local_seed node
      ✔ Check node is not started
      ✔ Start services
      ✖ Force nodes to sync
  ◼ Wait for Core peers to be connected
  ◼ Adjust Core mock time
  ◼ Start a miner
```

**Comment by dash-maverick** [comment]
Fix for that issue is currently under progress

**Comment by shumkov** [comment]
Fixed in #428 and #431

**Comment by SamKirby22** [comment]
@dashameter, as per discord convo, please retest. Should be fixed due to:

https://github.com/dashevo/dashmate/pull/437 (confirmed by Strophy)
+
https://github.com/dashevo/dashmate/pull/428
https://github.com/dashevo/dashmate/pull/431 (as above confirmed by shumkov)

**Comment by dashameter** [comment]
passed retest :+1:
