### ISSUE TITLE
Abstract preset and config to separate command

### ISSUE THREAD

**Issue by strophy** [dashevo/mn-bootstrap#61]
It is currently necessary to specify which network is being used in every single command. There are also a number of conditional checks for the current preset throughout the codebase to determine which network is being used, and each network has a slightly different configuration. This problem will be exacerbated when we eventually add a `mainnet` preset.

Would it be possible to separate the configuration into a `mn config` command (either with args or interactive) and store the current configuration somehow so the checks in the code can be generalized? Would it then become possible to change the command syntax to a simple `mn start`, with the preset selection done in advance, possibly with any other settings like IP, fullnode/masternode, port, BLS privkey, etc?

## Expected Behavior
Preset does not need to be specified in every command, making the tool more intuitive to use for non-technical users. Code is marginally easier to maintain by somehow abstracting preset checks.

## Current Behavior
`preset` must be specified in every command.

## Possible Solution
`mn config` command which must run first and stores config state somewhere in a file. This file would be cleared by a future `mn reset` command.

## Alternatives Considered
None, just thinking aloud here really.

**Comment by strophy** [comment]
OK, I have a WIP for the `config` command [here](https://github.com/strophy/mn-bootstrap/tree/config-util). Can you help evaluate my approach and see if this makes sense? It is based on the [Stream CLI](https://github.com/GetStream/stream-cli/tree/master/src/commands/config). A few questions:

1. Should we be saving the config all in one file with nested JSON, or multiple flat files?
2. Which specific config options do we want to save in the settings, and what remains in the .env files? Which settings should Docker Compose find in a file and which ones should be passed as arguments? Does it matter?
3. What is the best way to integrate `util/configs.js` in the existing functions, what objects should we be passing around, should we load settings through the util or just require the file directly? What sort of validation should we do on settings before loading them?
4. I'm having a lot of trouble with handling errors and exiting when conditions are met, there is always too much debug info output. How do I use the error handling properly?
5. `config:reset` is not implemented yet, I think I need to see (2) answered before trying this.
5. Lots of comments throughout the code where I could use advice on specific problems, but I can probably resolve most of these myself...

**Comment by shumkov** [comment]
Cool! I'll take a look:

1. I think, one JSON file is ok.
2. I would move everything to configs and pass all env variables directly to docker-compose. But there is one case when we need `.env` when we want to use Docker Compose CLI so in order to address it we could add `config:dump <name>` that will create `.env` with env vars for a specific config.
3. I would read configs in createDIContainer and store it in the container then other code can easily use it as a dependency.
4. I'll leave comments in code.

**Comment by strophy** [comment]
Thanks for the comments!

1. I had a go at changing it so configs are stored in a single file and it resulted in a lot of code that I found difficult to read because of difficulty handling the array indices. Is there a good reason to keep it all in a single file? Or a nicer way of modifying how the data is passed around? A function like `set` shouldn't need access to the entire array of all configs if it is just changing a single value of the current config. Would it be better to move all functions that deal with writing the file to the util class?
2. Cool, I totally agree on this one.
3. I had a go at this but failed due to limited understanding of awilix and DI. I think I'm having trouble switching my thinking to pass around functions that create objects, rather than passing the objects directly. Also, doesn't injecting all of these functions into the context result in a lot more drive and memory operations compared to only loading them when necessary?
4. Looking forward to working on this with you :)

**Comment by shumkov** [comment]
1. I feel it will be ok when we introduce 2 classes so it doesn't matter how you store data:
   * Config
       * `getName()` - returns name
       * `get(path)` - gets property value (use `lodash.get` to access nested properties)
       * `set(path, value)` - sets property value  (use `lodash.set` to access nested properties)
       *  `reset()` - resets config to default. you need to store `fromConfig` too in order to be able to reset to it.
   * `ConfigManager`
       * `loadConfigs()` - load configs from file
       * `saveConfigs()` - save configs to file
       * `getAllConfigs()` - returns all Config instances. 
       * `create(name, [fromConfig])` - creates a new config
       * `remove(name)` - removes a config
       * `setCurrentConfig(name)` - sets current config (`config:select`)
       * `getConfig(name)` - get config instance by name
 3. Container build and inject thing when it requires it so it's lazy loading as you described. You will need just to register `asClass(ConfigManager)` and then inject it when it needed. Also you need to call `loadConfigs` in command init (https://github.com/dashevo/mn-bootstrap/blob/245770e08400168b61a583a0f1dae695c41bd277/src/oclif/command/BaseCommand.js#L14)

**Comment by shumkov** [comment]
I’ve proposed another structure in your repo. I would also add validation of config with JSON Schema in order to maintain the right structure. I would add `Config#validate` and call it on `Config#set` to prevent of adding wrong options. Also, we need to validate the whole config file on the `read` and `write`.
