### ISSUE TITLE
Restart command

### ISSUE THREAD

**Issue by shumkov** [dashevo/mn-bootstrap#68]
## Expected Behavior

Restart command could be useful in case of local preset with image build path options. So updating code you can restart the node and rebuild stuff.

## Current Behavior

You need make two commands: stop and then start.

## Possible Solution

Implement reset command.

## Alternatives Considered

None

## Additional Context

None

**Comment by strophy** [comment]
To do this, I think we either need to store the config state somewhere (like in #61) or somehow use the `history` command to retrieve it?

**Comment by shumkov** [comment]
Yeah, we need the `config` command

**Comment by shumkov** [comment]
It's done on #152
