### ISSUE TITLE
Wrong version of core for testnet

### ISSUE THREAD

**Issue by strophy** [dashevo/mn-bootstrap#72]
The latest build from the `develop` branch (e.g. currently 0.16 RC1) should generally be used on testnet, but `mn-bootstrap` currently just uses the `latest` released version (0.15) instead. I will submit a PR for this if there are no objections?

## Expected Behavior
Use https://hub.docker.com/r/dashpay/dashd-develop images for testnet

## Current Behavior
Currently using https://hub.docker.com/r/dashpay/dashd

## Possible Solution
Specify `CORE_IMAGE` in preset files.

## Steps to Reproduce (for bugs)

1. mn start test [...]

## Context

Found this while trying to write documentation to use mn-bootstrap to deploy testnet masternodes.

## Your Environment

* Version used: 0.13.1
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop, server, or mobile):
* Link to your project:

**Comment by strophy** [comment]
Actually dashd-develop is not very useful either, since it is now showing Dash Core 0.17, when we currently want to be testing 0.16 RC1. Not sure if we should drop this or ask core devs if they can change their automated build rules on Docker Hub?

**Comment by shumkov** [comment]
Still actual?

**Comment by strophy** [comment]
No, we need to reconsider how the CI builds RC and develop branch images first. mn-bootstrap has all the changes it needs to support this already since we now allow the user to specify any docker image for core. Closing the issue for now.
