### ISSUE TITLE
evonet requires EXTERNAL_IP &  CORE_MASTERNODE_BLS_PRIV_KEY env vars to start

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/mn-bootstrap#8]
**recreate error:**

`cp .env.evonet .env` 

`docker-compose up`
```
ERROR: Missing mandatory value for "command" option interpolating ['dashd', '-conf=/dashd.conf', '-datadir=/data', '-masternodeblsprivkey=${CORE_MASTERNODE_BLS_PRIV_KEY:?err}', '-externalip=${CORE_EXTERNAL_IP:?err}'] in service "core": err
```
**issue:**
CORE_MASTERNODE_BLS_PRIV_KEY & CORE_EXTERNAL_IP need to be specified in .env file.
CORE_EXTERNAL_IP : not a problem!
CORE_MASTERNODE_BLS_PRIV_KEY & CORE_EXTERNAL_IP: requires masternode registration
- can a dummy key be used instead?
- this would (I assume) prevent the node from acting as a proper masternode - will this affect participation in evonet?

**Comment by thephez** [comment]
It does not actually require mn registration. You can run `bls generate` on the CLI of any Dash Core node to get valid BLS keys (they are not stored in the Dash Core wallet of the node they are generated on, so any node will do).

**Comment by shumkov** [comment]
Maybe we need to provide some helper scripts?

**Comment by shumkov** [comment]
@cloudwheels You don't need to deal with env using "start" command.

**Comment by cloudwheels** [comment]
@shumkov great! So we can close this.
Closing - no longer an issue due to release of CLI.
