### ISSUE TITLE
`--env-file` is not a valid option for `docker-compose up`

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/mn-bootstrap#9]
**recreate**
`docker-compose up --env-file=.env`

**issue**
readme.md specifies using  --env-file as method of passing .env to docker compose.
Docker compose returns valid options list: `--env-file` is not a valid option  for `docker-compose up` (only for `docker run`)

**sugged fix**
remove option from readme.md

**Comment by thephez** [comment]
I had the same issue originally due to my version of docker-compose (1.24 or something). It should work with the version recommended in the [pre-reqs](https://github.com/dashevo/mn-bootstrap#pre-requisites) - 1.25+.

**Comment by cloudwheels** [comment]
untested, but assume this works in v. > 1.25
